name: test-install

on:
  - push

jobs:
  py310-install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Conda
        uses: s-weigand/setup-conda@v1

      - name: Create py310 env
        run: |
          conda create -y -n setup-conda-env python=3.10

      - run: conda --version
      - run: python --version
      - run: which python

      - name: Replace python version in environment.yml
        shell: python
        run: |
          from pathlib import Path

          env_file = Path("environment.yml")
          env_file_text = env_file.read_text().replace("python~=3.7", "python~=3.10")
          env_file.write_text(env_file_text)

      - name: Show environment.yml
        run: cat environment.yml

      - name: Test conda environment
        run: |
          source activate setup-conda-env
          python --version
          which python
          conda env create --dry-run -f environment.yml -n test-environment
